### ISSUE TITLE
打包以后运行在手机上会崩溃（release模式）

### ISSUE THREAD

**Issue by greezi** [haltNoShut/YFAssistantTableView#2]
错误日志如下:
#0 Thread

NSInvalidArgumentException
**\* -[__NSCFString stringByReplacingCharactersInRange:withString:]: nil argument

0 CoreFoundation    ___exceptionPreprocess + 124
1 libobjc.A.dylib   objc_exception_throw + 56
2 CoreFoundation    -[NSException initWithCoder:]
3 Foundation    -[NSString stringByReplacingCharactersInRange:withString:] + 104
4 Exchange  0x0000000100020000 + 948572
5 Exchange  0x0000000100020000 + 950204

**Comment by greezi** [comment]
补充信息:

YFAssistantTableView.m

第122行

stitchingName = [originName stringByReplacingCharactersInRange:NSMakeRange(0,1) withString:[[NSString alloc]initWithUTF8String:&headerChar]];

originName 是 nil

**Comment by greezi** [comment]
刚刚给客户打包  运行崩溃 差点被老板打断腿

**Comment by haltNoShut** [comment]
你好，这是由于release编译过度优化引起的。解决方法 build settings 中搜索Code Generation,降低Optimization Level的等级或直接设None
