### ISSUE TITLE
返回的数据不一样的问题

### ISSUE THREAD

**Issue by shenshangjimiaoZG** [haltNoShut/YFAssistantTableView#4]
我看了你的代码，类似头部返回3条，而点击头部下面返回的数量却不一样，这个你没有实现吧。
我点击了一个cell，这个cell的下面的cell的返回的不一定和点击的cell的数量一样吧，这个没有封装好吧。

**Comment by haltNoShut** [comment]
没看明白问题描述，头不是什么意思?

**Comment by shenshangjimiaoZG** [comment]
@haltNoShut  就是说点击某个一个cell不是展开很多cell，展开的cell返回的数据不一定和被点击的cell的数据是一样。简单的说就是最顶层的cell数据是5条，而点击后展开的cell的数据是20条，这个展开的cell的返回数量就没有封装后。

**Comment by haltNoShut** [comment]
展开的cell上可以放tableview

**Comment by haltNoShut** [comment]
展开的cell上可以放tableview
